name: habit_stacker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  go_router: ^10.0.0
  get_it: ^7.6.4
  rive: ^0.11.13
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  build_runner: ^2.4.6
  isar_generator: ^3.1.0
  flutter_lints: ^3.0.0

dependency_overrides:
  analyzer: '5.13.0'
  source_gen: '1.4.0'
  test_api: '0.6.1'

flutter:
  uses-material-design: true