name: habit_stacker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar_community: 3.3.0-dev.3
  isar_community_flutter_libs: 3.3.0-dev.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^10.0.0
  get_it: ^7.6.4
  rive: ^0.11.13
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  rxdart: ^0.27.7
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_community_generator: 3.3.0-dev.3
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/CircleLoop.riv
    - assets/animations/CircleLoopOne.riv